project_name: godolint
release:
  github:
    owner: zabio3
    name: godolint
  name_template: '{{.Tag}}'
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: .
    ldflags: -s -w -X main.Version={{.Version}}  -X main.BuildDate={{.Date}}
    binary: godolint
