project_name: godolint
version: 2

release:
  github:
    owner: zabio3
    name: godolint
  name_template: '{{.Tag}}'

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: .
    ldflags: -s -w
    binary: godolint

archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE*
      - README*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
