name: go1.15
on: [push]
jobs:

  build:
    name: Build in Go1.15
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test
        run: go test -v -cover .
